site_name: Selected Topics in CS & Math
site_description: >-
    Selected topics in CS & Math explained in excruciating detail
repo_name: ankur-gupta/interviews
repo_url: https://github.com/ankur-gupta/interviews
edit_uri: edit/master/docs/
copyright: Copyright &copy; Ankur Gupta
theme:
    name: material
    custom_dir: overrides
    language: en_custom
    features:
        - tabs
    palette:
        scheme: preference
        primary: light green
        accent: light green
    icon:
        logo: fontawesome/solid/infinity
    favicon: assets/images/favicon.svg
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ankur-gupta
    - icon: fontawesome/brands/pied-piper-alt
      link: https://www.perfectlyrandom.org
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ankurguptawisc
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ankurio
plugins:
    - search:
        lang: en
    - git-revision-date-localized:
        type: timeago
        fallback_to_build_date: true
extra_javascript:
    - javascripts/config.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - def_list
    - pymdownx.highlight:
        use_pygments: true
        linenums: true
        linenums_style: pymdownx.inline
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.tabbed
    - footnotes
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.smartsymbols
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
    - meta
    - pymdownx.arithmatex:
        generic: true
nav:
    - Get Started:
        - Introduction: index.md
        - How to practice?: how-to-practice.md
    - Number Systems:
        - Decimal is not special: number-systems/decimal-is-not-special.md
        - Alien Two-Stick Measurement System: number-systems/alien-two-stick-measurement-system.md
        - Binary to Hexadecimal: number-systems/binary-to-hexadecimal.md
    - Algorithmic Complexity:
        - Space is not Time: algorithmic-complexity/space-is-not-time.md
        - Precision is important: algorithmic-complexity/precision-is-important.md
    - Tips & Tricks:
        - Hashing to find strangers: tips-and-tricks/hashing-to-find-strangers.md
        - Rolling Window: tips-and-tricks/rolling-window.md
